apiVersion: v1
kind: ConfigMap
metadata:
  name: mediamtx-config
  namespace: {{ .Values.namespace }}
data:
  mediamtx.yml: |
    logLevel: {{ .Values.mediamtxConfig.logLevel }}
    api: yes
    apiAddress: {{ .Values.mediamtxConfig.apiAddress }}
    rtsp: yes
    rtspAddress: {{ .Values.mediamtxConfig.rtspAddress }}
    webrtc: yes
    webrtcAddress: {{ .Values.mediamtxConfig.webrtcAddress }}
    webrtcLocalUDPAddress: {{ .Values.mediamtxConfig.webrtcLocalUDPAddress }}
    paths:
      {{ .Values.mediamtxConfig.pathName }}:
        source: {{ .Values.mediamtxConfig.pathSource }}
