apiVersion: v1
kind: Service
metadata:
  name: mediamtx-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mediamtx
  ports:
    - name: rtsp-tcp
      protocol: TCP
      port: {{ .Values.service.mediamtx.rtsp.port }}
      targetPort: {{ .Values.service.mediamtx.rtsp.port }}
      nodePort: {{ .Values.service.mediamtx.rtsp.nodePort }}
    - name: webrtc-http
      protocol: TCP
      port: {{ .Values.service.mediamtx.webrtcHttp.port }}
      targetPort: {{ .Values.service.mediamtx.webrtcHttp.port }}
      nodePort: {{ .Values.service.mediamtx.webrtcHttp.nodePort }}
    - name: webrtc-udp
      protocol: UDP
      port: {{ .Values.service.mediamtx.webrtcUdp.port }}
      targetPort: {{ .Values.service.mediamtx.webrtcUdp.port }}
      nodePort: {{ .Values.service.mediamtx.webrtcUdp.nodePort }}
    - name: api
      protocol: TCP
      port: {{ .Values.service.mediamtx.api.port }}
      targetPort: {{ .Values.service.mediamtx.api.port }}
      nodePort: {{ .Values.service.mediamtx.api.nodePort }}

---
apiVersion: v1
kind: Service
metadata:
  name: human-detector-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: human-detector
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.detector.http.port }}
      targetPort: {{ .Values.service.detector.http.port }}
      nodePort: {{ .Values.service.detector.http.nodePort }}
